### PR TITLE
Create a Home page

### PR DESCRIPTION
**Pull request by joquendo**
Create a Home page and add .DS_Store to the .gitignore file

### CODE REVIEW

**Review by vijayxtreme — CHANGES_REQUESTED** [review]
Hey James,  I think this looks good - but we may want to take off tracking for the .DS_Store in the .gitignore file.  Can you work with @Schraut to make sure that the .gitignore is the one we use on the repo now?
Also, I think the HomePage could be refactored into the Page element that @Schraut created.  Can you pair with him?

**Comment by joquendo** [comment]
Hey @vijayxtreme, sure, I'll pair up with @Schraut. Thanks.

**Comment by vijayxtreme** [comment]
Closing

**Comment by joquendo** [comment]
@vijayxtreme @Schraut, following up on this. Noticed it was closed without merge. Is there any feedback? Thanks.

**Pull request closed without merging**
